<?php

namespace AppBundle\Repository;

use Gedmo\Tree\Entity\Repository\ClosureTreeRepository;
use AppBundle\Repository\TranslatableRepository;

/**
 * PageTreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageTreeRepository extends ClosureTreeRepository
{
    use TranslatableRepository;

    /**
     * Returns all posts
     *
     * @return array
     */
    public function findAll()
    {
        $qb = $this->createQueryBuilder('post');

        return $this->getResult($qb, 'kg');
    }
}
